<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ $recipe['name'] }}
        </h2>
    </x-slot>

    <div class="py-10 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
        <div class="bg-white shadow rounded-xl p-6">
            <img src="{{ $recipe['image'] }}" alt="recipe image" class="w-full h-64 object-cover rounded mb-6">

            <div class="grid grid-cols-1 md:grid-cols-4 gap-4 text-sm text-gray-600 mb-8">
                <p><strong>⏱ Duration:</strong> {{ $recipe['duration'] }}</p>
                <p><strong>🍽 Servings:</strong> {{ $recipe['servings'] }}</p>
                <p><strong>📊 Difficulty:</strong> {{ ucfirst($recipe['difficulty']) }}</p>
                <p><strong>🔥 Calories:</strong> {{ $recipe['calories'] ?? 'N/A' }} kcal</p>
            </div>

            <h3 class="text-lg font-semibold mb-2">📝 Description</h3>
            <p class="text-gray-700 mb-4">{{ $recipe['description'] }}</p>

            <h3 class="text-lg font-semibold mb-2">🥗 Ingredients</h3>
            <ul class="list-disc pl-5 text-gray-700 mb-4">
                @foreach ($recipe['ingredients'] as $ingredient)
                    <li>{{ $ingredient }}</li>
                @endforeach
            </ul>

            <h3 class="text-lg font-semibold mb-2">👨‍🍳 Instructions</h3>
            <p class="text-gray-700 whitespace-pre-line">{{ $recipe['instructions'] }}</p>

            <<div class="mt-8 flex justify-end">
    <div>
        <button onclick="handleGroceryList()" 
         class="text-sm bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-600">
          🛒 Generate Shopping List
        </button>

        <!-- Hidden textarea for copying -->
        <textarea id="groceryListText" class="hidden"></textarea>

        <!-- Copy to Clipboard Confirmation -->
        <div id="copyMessage" class="hidden text-green-600 mt-2 font-medium">Copied to clipboard! ✅</div>

        <button class="text-sm bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 mx-2">
            🤍 Save
        </button>
        <button class="text-sm bg-red-700 text-white px-4 py-2 rounded hover:bg-red-800 my-2">
            📅 Add to Plan
        </button>

        @php
            $ingredients = implode("%0A- ", $recipe['groceryLists']);
            $waMessage = "🛒 CookEase Shopping List:%0A- " . $ingredients;
        @endphp

        <a href="https://wa.me/?text={{ $waMessage }}" 
           target="_blank"
           class="inline-block mt-4 bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded">
            📤 Share on WhatsApp
        </a>
    </div>
</div>


    <!-- Hidden print section -->
    <div id="printableGroceryList" class="hidden print:block p-6 max-w-md mx-auto bg-white">
        <h2 class="text-xl font-bold mb-4">🛒 Grocery Shopping List</h2>
        <ul class="list-disc pl-6 text-gray-800 space-y-1">
            @foreach ($recipe['groceryLists'] as $item)
                <li>{{ ucfirst($item) }}</li>
            @endforeach
        </ul>
        <p class="mt-6 text-sm text-gray-500">Generated by CookEase - {{ now()->toDateString() }}</p>
    </div>

        <script>
        function handleGroceryList() {
        const items = @json($recipe['groceryLists']);
        const text = "🛒 CookEase Shopping List:\n\n" + items.map(item => "- " + item).join("\n");

        // Copy to clipboard
        const textarea = document.getElementById('groceryListText');
        textarea.value = text;
        textarea.classList.remove('hidden');
        textarea.select();
        document.execCommand('copy');
        textarea.classList.add('hidden');

        // Show copied message
        const message = document.getElementById('copyMessage');
        message.classList.remove('hidden');
        setTimeout(() => message.classList.add('hidden'), 2000);

        // Trigger print (optional)
        window.print();
        }
        </script>
  

</x-app-layout>
